---
title: "Covid19 progression"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: fill
    theme: journal
runtime: shiny
---

```{r global, include=FALSE}
source(file = "global.R", echo = F, encoding = "UTF-8")
```

# Inputs {.sidebar}

On peut choisir ici quels pays on cherche à comparer.

```{r}
pickerInput(inputId = "Selection", label = "Countries selected:",
            choices = Countries, 
            selected = c("FRA", "ITA", "ESP", "GBR", "DEU"),
            multiple = T,
            options = list(`actions-box` = TRUE))

selectInput(inputId = "Type", label = "Type:",
            choices = c("confirmed", "deaths", "recovered"),
            selected = "confirmed",
            multiple = F)

```

Progression
=====================================

```{r}
PLOT =
  function(){
    Panel_data %>%
      filter(iso3c %in% input$Selection) %>%
      select(iso3c, country, 
             Number = input$Type, date, population) %>%
      filter(Number>0)
  }
```

Row {.tabset .tabset-fade}
-------------------------------------

### Echelle simple
```{r}
renderPlot({
  PLOT_rel_abs(plot = PLOT())
})
```

### Echelle logarithmique
```{r}
renderPlot({
  PLOT_rel_abs(plot = PLOT()) +
    scale_y_log10()
})
```

Echelle log-log
=====================================

```{r}
renderPlot({
  Daily_data %>%
    filter(iso3c %in% input$Selection,
           Type == input$Type) %>%
    ggplot(mapping = aes(
      x = Number,
      y = Daily_cases,
      colour = country,
      group = country
    )) +
    # geom_line()+
    geom_smooth(se = F) +
    scale_x_log10() +
    scale_y_log10() +
    theme(legend.position = "bottom") +
    xlab(label = "Total confirmed cases") +
    ylab(label = "New confirmed cases")
})
```

Moyennes glissantes
============

```{r}
renderPlot({
  Daily_data %>%
    filter(iso3c %in% input$Selection,
           Type != "recovered") %>%
    group_by(Type, iso3c) %>%
    mutate(Mobile = zoo::rollmean(x = Daily_cases,
                                  k = 7, na.pad = T)) %>%
    ungroup() %>%
    ggplot(mapping = aes(x = date)) +
    geom_line(mapping = aes(y = Mobile, colour = country)) +
    scale_y_log10() +
    facet_wrap(facets = ~ Type, scales = "free_y") +
    theme(legend.position = "bottom") +
    xlab(label = "Date") +
    ylab(label = "Daily cases")
})
```